import os
from dotenv import load_dotenv

load_dotenv()

USERS_TABLE = f'''
--создание таблици профиля
create table if not exists users
(
    id         integer generated by default as identity
        constraint user_pk
            primary key,
    name       text      not null,
    email      text      not null,
    created_at timestamp not null
);

alter table users
    owner to {os.getenv("PSQL_DB_USER")};
'''

WALLET_TABLE = f'''
--создание таблици профиля
create table if not exists wallet
(
    id           integer generated by default as identity
        constraint wallet_pk
            primary key,
    user_id      integer          not null
        constraint wallet_users_id_fk
            references users,
    user_balance double precision not null
);

alter table wallet
    owner to {os.getenv("PSQL_DB_USER")};
'''

TRANSACTION_TABLE = f'''
--создание таблици профиля
create table if not exists transactions
(
    id             integer generated by default as identity
        constraint transactions_pk
            primary key,
    user_id        integer          not null
        constraint transactions_users_id_fk
            references users,
    from_wallet_id integer          not null
        constraint transactions_wallet_id_fk_2
            references wallet,
    to_wallet_id   integer          not null
        constraint transactions_wallet_id_fk
            references wallet,
    before         double precision not null,
    amount         double precision not null,
    after          double precision not null,
    creation_date  timestamp
);

alter table transactions
    owner to {os.getenv("PSQL_DB_USER")};
'''